
; ERB Binary Substrate - Generated Assembly (ARM64 / Apple Silicon)
; Generated from rulebook formulas - DO NOT HAND-EDIT
;
; This file is GENERATED by inject-into-binary.py
; The formulas are the source of truth, not this assembly.


; String runtime for ERB Binary Substrate (ARM64 / Apple Silicon)
; Calling convention: Apple ARM64 ABI

    .text
    .p2align 2

; bool _string_equals(const char* s1, size_t len1, const char* s2, size_t len2)
; x0 = s1, x1 = len1, x2 = s2, x3 = len2
; Returns 1 if strings are equal, 0 otherwise in w0
    .globl _string_equals
_string_equals:
    cmp x1, x3                  ; Compare lengths first
    b.ne Lstr_eq_false
    cbz x1, Lstr_eq_true        ; If both empty, equal

    ; Compare byte by byte
    mov x4, #0                  ; index
Lstr_eq_loop:
    ldrb w5, [x0, x4]
    ldrb w6, [x2, x4]
    cmp w5, w6
    b.ne Lstr_eq_false
    add x4, x4, #1
    cmp x4, x1
    b.lt Lstr_eq_loop

Lstr_eq_true:
    mov w0, #1
    ret

Lstr_eq_false:
    mov w0, #0
    ret

; char* _string_concat(char* dest, const char* s1, size_t len1, const char* s2, size_t len2)
; x0 = dest, x1 = s1_ptr, x2 = s1_len, x3 = s2_ptr, x4 = s2_len
; Returns dest in x0, total length in x1
    .globl _string_concat
_string_concat:
    stp x29, x30, [sp, #-16]!
    mov x29, sp
    stp x19, x20, [sp, #-16]!
    stp x21, x22, [sp, #-16]!

    mov x19, x0                 ; save dest
    mov x20, x2                 ; save s1_len
    mov x21, x4                 ; save s2_len

    ; Copy s1 to dest
    mov x5, #0                  ; index
    cbz x2, Lconcat_s2          ; skip if s1 empty
Lconcat_s1_loop:
    ldrb w6, [x1, x5]
    strb w6, [x0, x5]
    add x5, x5, #1
    cmp x5, x2
    b.lt Lconcat_s1_loop

Lconcat_s2:
    ; Copy s2 after s1
    add x0, x19, x20            ; dest + s1_len
    mov x5, #0                  ; index
    cbz x21, Lconcat_done       ; skip if s2 empty
Lconcat_s2_loop:
    ldrb w6, [x3, x5]
    strb w6, [x0, x5]
    add x5, x5, #1
    cmp x5, x21
    b.lt Lconcat_s2_loop

Lconcat_done:
    mov x0, x19                 ; return dest ptr
    add x1, x20, x21            ; return total length

    ldp x21, x22, [sp], #16
    ldp x19, x20, [sp], #16
    ldp x29, x30, [sp], #16
    ret

; int_to_string: convert integer to string
; x0 = buffer, x1 = integer value
; Returns: x0 = buffer ptr, x1 = string length
    .globl _int_to_string
_int_to_string:
    stp x29, x30, [sp, #-16]!
    mov x29, sp
    stp x19, x20, [sp, #-16]!
    stp x21, x22, [sp, #-16]!

    mov x19, x0                 ; save buffer start
    mov x20, x0                 ; current position
    mov x2, x1                  ; value to convert

    ; Handle negative
    cmp x2, #0
    b.ge Lits_positive
    neg x2, x2
    mov w3, #'-'
    strb w3, [x20], #1

Lits_positive:
    mov x21, x20                ; start of digits

    ; Generate digits in reverse
    mov x3, #10
Lits_loop:
    udiv x4, x2, x3             ; quotient
    msub x5, x4, x3, x2         ; remainder = x2 - (x4 * 10)
    add w5, w5, #'0'
    strb w5, [x20], #1
    mov x2, x4
    cbnz x2, Lits_loop

    ; Calculate length
    sub x22, x20, x19           ; length

    ; Reverse digits (x21 = start, x20-1 = end)
    sub x20, x20, #1            ; point to last digit
Lits_reverse:
    cmp x21, x20
    b.ge Lits_done
    ldrb w3, [x21]
    ldrb w4, [x20]
    strb w4, [x21], #1
    strb w3, [x20]
    sub x20, x20, #1
    b Lits_reverse

Lits_done:
    mov x0, x19                 ; return buffer ptr
    mov x1, x22                 ; return length

    ldp x21, x22, [sp], #16
    ldp x19, x20, [sp], #16
    ldp x29, x30, [sp], #16
    ret

    .data
    .globl _str_true
_str_true:
    .asciz "true"
    .globl _str_false
_str_false:
    .asciz "false"



    .data
    .globl str_0
str_0:
    .asciz " "
    .globl str_0_len
str_0_len:
    .quad 1

    ; Static result buffers for string concatenation
    .bss
    .globl _result_buf_eval_customers_full_name
    .p2align 3
_result_buf_eval_customers_full_name:
    .space 1024

    .text

    .globl _eval_customers_full_name
    .p2align 2
_eval_customers_full_name:
    stp x29, x30, [sp, #-16]!
    mov x29, sp
    stp x19, x20, [sp, #-16]!
    stp x21, x22, [sp, #-16]!
    stp x23, x24, [sp, #-16]!
    sub sp, sp, #256
    mov x19, x0
    ldr x0, [x19, #48]
    ldr x1, [x19, #56]
    str x0, [sp, #16]
    str x1, [sp, #24]
    adrp x0, str_0@PAGE
    add x0, x0, str_0@PAGEOFF
    mov x1, #1
    str x0, [sp, #32]
    str x1, [sp, #40]
    ldr x0, [x19, #64]
    ldr x1, [x19, #72]
    str x0, [sp, #48]
    str x1, [sp, #56]
    ldr x0, [sp, #16]
    ldr x1, [sp, #24]
    adrp x22, _result_buf_eval_customers_full_name@PAGE
    add x22, x22, _result_buf_eval_customers_full_name@PAGEOFF
    ldr x4, [sp, #40]
    ldr x3, [sp, #32]
    mov x2, x1
    mov x1, x0
    mov x0, x22
    bl _string_concat
    ldr x4, [sp, #56]
    ldr x3, [sp, #48]
    mov x2, x1
    mov x1, x0
    mov x0, x22
    bl _string_concat
    add sp, sp, #256
    ldp x23, x24, [sp], #16
    ldp x21, x22, [sp], #16
    ldp x19, x20, [sp], #16
    ldp x29, x30, [sp], #16
    ret

