@startuml
skinparam classAttributeIconSize 0

class Customers {
  +CustomerId: String
  +Customer: String
  +EmailAddress: String
  +FirstName: String
  +LastName: String
  +Orders: String
  --
  /FullName: String  {derived}
}

class Orders {
  +OrderId: String
  +OrderNumber: Integer
  +Customer: String
  +CustomerEmailAddress: String
  +CustomerFullName: String
  --
  /Name: String  {derived}
}

@enduml