@startuml
skinparam classAttributeIconSize 0

class Customers {
  +CustomerId: String
  +Customer: String
  +EmailAddress: String
  +FirstName: String
  +LastName: String
  --
  /FullName: String  {derived}
}

@enduml