-- ============================================================================
-- DROP AND CREATE TABLES - Clean slate + Normalized schema
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Tables: 1
-- Total Raw Fields: 5
-- ============================================================================

-- ============================================================================
-- DROP SPECIFIC OBJECTS - Only dropping objects that will be recreated
-- ============================================================================

-- Drop functions (order: first, because views depend on them)
DROP FUNCTION IF EXISTS calc_customers_full_name(TEXT) CASCADE;

-- Drop views (order: second, because they depend on tables)
DROP VIEW IF EXISTS vw_customers CASCADE;

-- Drop tables (order: last, after dependent objects are removed)
DROP TABLE IF EXISTS customers CASCADE;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

CREATE TABLE customers (
  customer_id                         TEXT                 PRIMARY KEY,
  customer                            TEXT                ,
  email_address                       TEXT                ,
  first_name                          TEXT                ,
  last_name                           TEXT                
);

