-- ============================================================================
-- DROP AND CREATE TABLES - Clean slate + Normalized schema
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Tables: 2
-- Total Raw Fields: 7
-- ============================================================================

-- ============================================================================
-- DROP SPECIFIC OBJECTS - Only dropping objects that will be recreated
-- ============================================================================

-- Drop functions (order: first, because views depend on them)
DROP FUNCTION IF EXISTS calc_customers_full_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_orders_customer_email_address(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_orders_customer_full_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_orders_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_customers_customer(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_customers_email_address(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_customers_first_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_customers_last_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_orders_order_number(TEXT) CASCADE;

-- Drop views (order: second, because they depend on tables)
DROP VIEW IF EXISTS vw_customers CASCADE;
DROP VIEW IF EXISTS vw_orders CASCADE;

-- Drop tables (order: last, after dependent objects are removed)
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS orders CASCADE;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

CREATE TABLE customers (
  customer_id                         TEXT                 PRIMARY KEY,
  customer                            TEXT                ,
  email_address                       TEXT                ,
  first_name                          TEXT                ,
  last_name                           TEXT                
);

CREATE TABLE orders (
  order_id                            TEXT                 PRIMARY KEY,
  order_number                        INTEGER             ,
  customer                            TEXT                
);

