-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Views: 2
-- ============================================================================

CREATE OR REPLACE VIEW vw_customers WITH (security_invoker = ON) AS
SELECT
  t.customer_id,
  t.customer,
  t.email_address,
  t.first_name,
  t.last_name,
  calc_customers_full_name(t.customer_id) AS full_name
FROM customers t;

