-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Views: 2
-- ============================================================================

CREATE OR REPLACE VIEW vw_is_everything_a_language WITH (security_invoker = ON) AS
SELECT
  t.is_everything_a_language_id,
  t.name,
  t.argument_name,
  t.argument_category,
  t.step_type,
  t.statement,
  t.formalization,
  t.related_candidate_name,
  t.related_candidate_id,
  t.evidence_from_rulebook,
  t.notes
FROM is_everything_a_language t;

CREATE OR REPLACE VIEW vw_language_candidates WITH (security_invoker = ON) AS
SELECT
  t.language_candidate_id,
  t.name,
  calc_language_candidates_is_a_family_feud_top_answer(t.language_candidate_id) AS is_a_family_feud_top_answer,
  t.category,
  t.can_be_held,
  t.meaning_is_serialized,
  t.requires_parsing,
  t.is_ongology_descriptor,
  t.has_syntax,
  t.chosen_language_candidate,
  calc_language_candidates_family_feud_mismatch(t.language_candidate_id) AS family_feud_mismatch,
  t.sort_order,
  calc_language_candidates_family_fued_question(t.language_candidate_id) AS family_fued_question,
  t.has_identity,
  calc_language_candidates_relationship_to_concept(t.language_candidate_id) AS relationship_to_concept,
  t.distance_from_concept,
  calc_language_candidates_category_contains_language(t.language_candidate_id) AS category_contains_language,
  calc_language_candidates_has_grammar(t.language_candidate_id) AS has_grammar
FROM language_candidates t;

