-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Views: 2
-- ============================================================================

CREATE OR REPLACE VIEW vw_customers WITH (security_invoker = ON) AS
SELECT
  t.customer_id,
  t.customer,
  t.email_address,
  t.first_name,
  t.last_name,
  calc_customers_full_name(t.customer_id) AS full_name,
  calc_customers_orders(t.customer_id) AS orders
FROM customers t;

CREATE OR REPLACE VIEW vw_orders WITH (security_invoker = ON) AS
SELECT
  t.order_id,
  calc_orders_name(t.order_id) AS name,
  t.order_number,
  t.customer,
  calc_orders_customer_email_address(t.order_id) AS customer_email_address,
  calc_orders_customer_full_name(t.order_id) AS customer_full_name
FROM orders t;

