-- ============================================================================
-- INSERT DATA - Load data from rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- ============================================================================

INSERT INTO customers (customer_id, customer, email_address, first_name, last_name)
VALUES ('cust0001', 'CUST0001', 'jane.smith@email.com', 'Jane', 'Smith');

INSERT INTO customers (customer_id, customer, email_address, first_name, last_name)
VALUES ('cust0002', 'CUST0002', 'john.doe@email.com', 'John', 'Doe');

INSERT INTO customers (customer_id, customer, email_address, first_name, last_name)
VALUES ('cust0003', 'CUST0003', 'emily.jones@email.com', 'Emily', 'Jones');

